repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --explicit-package-bases
        files: ^intermedio/m03-fastapi/
        types: [python]
        additional_dependencies:
          - fastapi
          - sqlalchemy
          - pydantic
          - pytest
          - httpx
          - types-python-jose
          - types-passlib