repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy-modulos-generales
        args:
          - --strict
          - --explicit-package-bases
        files: ^(fundamental/m01-entorno-herramientas/|intermedio/m0[1-7]-)/
        types: [python]
        additional_dependencies:
          - pytest
          - hypothesis
          - sqlalchemy
          - alembic
          - fastapi
          - pydantic
          - httpx
          - types-python-jose
          - types-passlib

  - repo: local
    hooks:
      - id: mypy-m08-ciencia-datos
        name: mypy m08-ciencia-datos
        entry: mypy
        language: python
        files: ^intermedio/m08-ciencia-datos/
        types: [python]
        args:
          - --config-file=intermedio/m08-ciencia-datos/pyproject.toml
          - --strict
          - --explicit-package-bases
        additional_dependencies:
          - mypy==1.15.0
          - joblib
          - scipy
          - scikit-learn==1.5.2
          - pandas
          - pandas-stubs